# -*- coding: utf-8 -*-
"""Matrix_Tensor_Video_Decomposition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhkIDRILd5yi680UsZF49XKBVkcZucoQ

# Matrix & Tensor Decomposition for Video Background Separation

This project investigates how matrix and tensor decomposition methods can be
used to separate background and foreground in videos. Background subtraction
is essential for applications such as surveillance, motion detection,
object tracking, and video analytics.

We compare six methods:

### **Matrix-based**
- RPCA (Robust PCA)
- CUR Decomposition
- IRCUR (Iterated Robust CUR)

### **Tensor-based**
- CP Decomposition
- Tucker Decomposition
- RTCUR (True Fiber CUR for Tensors)

We evaluate each method on:
1. Synthetic data
2. Tensor synthetic data
3. Real video frames

We compare performance using:
- Reconstruction accuracy (SNR)
- Computational time
- Visual background/foreground separation quality
"""

!pip install tensorly
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import cv2
from numpy.linalg import svd
import tensorly as tl
from tensorly.decomposition import tucker, parafac
tl.set_backend("numpy")

from skimage.metrics import structural_similarity as ssim

"""**1. Utility Functions**"""

def to_float(X):
    X = np.asarray(X, dtype=np.float64)
    return np.nan_to_num(X)

def fro_norm(X):
    return np.sqrt(np.sum(X**2))

def snr_db(true, est):
    true, est = to_float(true), to_float(est)
    err = fro_norm(true - est)
    if err == 0:
        err = 1e-12
    return 20 * np.log10(fro_norm(true) / err)

def hard_threshold(X, tau):
    return np.where(np.abs(X) > tau, X, 0)

def truncated_svd(X, k):
    U, S, Vt = np.linalg.svd(X, full_matrices=False)
    k = min(k, len(S))
    return U[:, :k], S[:k], Vt[:k, :]

def singular_value_thresholding(X, tau):
    U, S, Vt = svd(X, full_matrices=False)
    S2 = np.maximum(S - tau, 0)
    return U @ np.diag(S2) @ Vt

def soft_thresholding(X, tau):
    return np.sign(X) * np.maximum(np.abs(X) - tau, 0)

"""## 1.1 Background

Background subtraction aims to identify moving objects (foreground)
in a video by separating them from the static background. This is
commonly formulated as:

**Video = Background (Low-Rank) + Foreground (Sparse or Dynamic)**

Matrix and tensor decomposition techniques are ideal for this because:
- Background across frames is highly correlated → low rank
- Moving objects appear only in some frames → sparse

## 1.2 Problem Definition

Given a video represented as:
- A **matrix** (vectorized frames) or
- A **tensor** (height × width × time)

Find:
- **L** → low-rank background
- **S** → sparse or dynamic foreground

We evaluate the performance of 6 decomposition methods in reconstructing L and S.

**2. MATRIX METHODS**

2.1 RPCA
"""

def rpca(D, lam=None, mu=None, tol=1e-7, max_iter=300):
    D = to_float(D)
    m, n = D.shape

    if lam is None:
        lam = 1 / np.sqrt(max(m, n))
    if mu is None:
        mu = (m * n) / (4 * np.sum(np.abs(D)) + 1e-8)

    L = np.zeros_like(D)
    S = np.zeros_like(D)
    Y = np.zeros_like(D)

    for _ in range(max_iter):
        L = singular_value_thresholding(D - S + Y / mu, 1 / mu)
        S = soft_thresholding(D - L + Y / mu, lam / mu)
        R = D - L - S
        Y += mu * R

        if fro_norm(R) / fro_norm(D) < tol:
            break

    return L, S

"""2.2 CUR Decomposition"""

def cur_decomposition(D, k=10):
    m, n = D.shape

    col_energy = np.sum(D**2, axis=0)
    row_energy = np.sum(D**2, axis=1)

    col_idx = np.argsort(col_energy)[-k:]
    row_idx = np.argsort(row_energy)[-k:]

    C = D[:, col_idx]
    R = D[row_idx, :]
    U = D[np.ix_(row_idx, col_idx)]

    U_pinv = np.linalg.pinv(U)
    L = C @ U_pinv @ R

    return L

"""2.3 IRCUR (Iterated Robust CUR)"""

def ircur(D, r=10, z0=3, gamma=0.95, max_iter=8):

    Dn = D / (np.max(np.abs(D)) + 1e-8)
    L = np.zeros_like(Dn)
    S = np.zeros_like(Dn)
    z = z0

    for _ in range(max_iter):
        S = hard_threshold(Dn - L, z)
        z *= gamma

        R = Dn - S
        row_e = np.sum(R**2, axis=1)
        col_e = np.sum(R**2, axis=0)

        rows = np.argsort(row_e)[-r:]
        cols = np.argsort(col_e)[-r:]

        C = R[:, cols]
        R_sub = R[rows, :]
        U = R[np.ix_(rows, cols)]

        Uu, Ss, Vv = truncated_svd(U, r)
        U_pinv = Vv.T @ np.diag(1 / (Ss + 1e-12)) @ Uu.T

        L = C @ U_pinv @ R_sub

    L *= np.max(np.abs(D))
    S *= np.max(np.abs(D))
    return L, S

"""**3. TENSOR METHODS**

3.1 CP Decomposition

"""

def cp_reconstruct(X, rank=5):
    fac = parafac(X, rank=rank)
    return tl.cp_to_tensor(fac)

"""3.2 Tucker Decomposition"""

def tucker_reconstruct(X, ranks=(10,10,3)):
    core, factors = tucker(X, rank=ranks)
    return tl.tucker_to_tensor((core, factors))

"""3.3 RTCUR (True Fiber CUR Tensor Decomposition)"""

def rtcur_reconstruct(X, ranks=(10,10,3)):
    X = to_float(X)
    norm = fro_norm(X)
    Xn = X / (norm + 1e-12)
    factors = []

    for mode, r in enumerate(ranks):
        X_un = tl.unfold(Xn, mode)
        e_rows = np.sum(X_un**2, axis=1)
        e_cols = np.sum(X_un**2, axis=0)

        row_idx = np.argsort(e_rows)[-r:]
        col_idx = np.argsort(e_cols)[-r:]

        C = X_un[:, col_idx]
        R = X_un[row_idx, :]
        U = X_un[np.ix_(row_idx, col_idx)]

        U_pinv = np.linalg.pinv(U)
        factor = C @ U_pinv
        factors.append(factor)

    core = Xn
    for mode, F in enumerate(factors):
        core = tl.tenalg.mode_dot(core, np.linalg.pinv(F), mode=mode)

    L = core
    for mode, F in enumerate(factors):
        L = tl.tenalg.mode_dot(L, F, mode=mode)

    return L * norm, None

"""**4. Synthetic Data Generation**

"""

def generate_background(H=128, W=128):
    y,x = np.ogrid[:H,:W]
    center = (H/2, W/2)
    r = np.sqrt((x-center[1])**2 + (y-center[0])**2)
    return 255*np.exp(-((r-40)**2)/(2*20**2))

def add_noise(img, sigma=0.02):
    img = img / 255
    noise = np.random.normal(0, sigma, img.shape)
    return np.clip(img + noise, 0, 1) * 255

def build_tensor(bg, frames=10):
    return np.stack([add_noise(bg) for _ in range(frames)], axis=2)

"""**5. MATRIX EXPERIMENTS**"""

bg = generate_background()
H, W = bg.shape
frames = [add_noise(bg) for _ in range(10)]

D = np.column_stack([f.reshape(-1) for f in frames])

print("Running RPCA")
t1 = time.time()
L_rpca, S_rpca = rpca(D)
t_rpca = time.time() - t1

print("Running CUR")
t1 = time.time()
L_cur = cur_decomposition(D, k=10)
t_cur = time.time() - t1

print("Running IRCUR")
t1 = time.time()
L_ircur, S_ircur = ircur(D, r=10)
t_ircur = time.time() - t1

bg_rpca = L_rpca[:,0].reshape(H, W)
fg_rpca = S_rpca[:,0].reshape(H, W)
bg_cur = L_cur[:,0].reshape(H, W)
fg_cur = (D - L_cur)[:,0].reshape(H, W)
bg_ircur = L_ircur[:,0].reshape(H, W)
fg_ircur = S_ircur[:,0].reshape(H, W)

print("\nSNR RESULTS (Synthetic Matrix)")
print("RPCA :", snr_db(bg.reshape(-1), L_rpca[:,0]))
print("CUR  :", snr_db(bg.reshape(-1), L_cur[:,0]))
print("IRCUR:", snr_db(bg.reshape(-1), L_ircur[:,0]))

"""SNR Comparison (Matrix Methods)"""

X = build_tensor(bg, frames=10)

print("\nRunning Tucker")
T_tucker = tucker_reconstruct(X)

print("Running CP")
T_cp = cp_reconstruct(X, rank=5)

print("Running RTCUR")
T_rtcur, _ = rtcur_reconstruct(X, ranks=(10,10,3))

print("\nSNR RESULTS (Tensor)")
print("Tucker:", snr_db(X[:,:,0], T_tucker[:,:,0]))
print("CP    :", snr_db(X[:,:,0], T_cp[:,:,0]))
print("RTCUR :", snr_db(X[:,:,0], T_rtcur[:,:,0]))

"""Matrix Method Comparison Bar Plot"""

methods_matrix = ["RPCA", "CUR", "IRCUR"]

snr_vals_matrix = [
    snr_db(bg.reshape(-1), L_rpca[:,0]),   # RPCA SNR
    snr_db(bg.reshape(-1), L_cur[:,0]),    # CUR SNR
    snr_db(bg.reshape(-1), L_ircur[:,0])   # IRCUR SNR
]

plt.figure(figsize=(8,5))
plt.bar(methods_matrix, snr_vals_matrix,
        color=["#4C72B0", "#55A868", "#C44E52"])  # same colors

plt.title("Matrix Methods SNR Comparison", fontsize=16)
plt.ylabel("SNR (dB)")
plt.grid(axis='y', alpha=0.4)

plt.show()

"""Heatmaps for Foreground Intensities"""

plt.figure(figsize=(14,4))

plt.subplot(1,3,1)
plt.imshow(fg_rpca, cmap="inferno")
plt.title("RPCA Foreground Heatmap")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(fg_cur, cmap="inferno")
plt.title("CUR Foreground Heatmap")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(fg_ircur, cmap="inferno")
plt.title("IRCUR Foreground Heatmap")
plt.axis("off")

plt.tight_layout()
plt.show()

# Compute SSIM for matrix methods
ssim_rpca = ssim(bg, bg_rpca, data_range=bg_rpca.max() - bg_rpca.min())
ssim_cur  = ssim(bg, bg_cur,  data_range=bg_cur.max()  - bg_cur.min())
ssim_ircur= ssim(bg, bg_ircur,data_range=bg_ircur.max()- bg_ircur.min())

print("SSIM - RPCA :", ssim_rpca)
print("SSIM - CUR  :", ssim_cur)
print("SSIM - IRCUR:", ssim_ircur)

"""Radar Chart (Spider Plot) for Ranking Methods"""

import matplotlib.pyplot as plt
import numpy as np

labels = np.array(["SNR", "SSIM", "Runtime"])

RPCA_vals  = np.array([snr_db(bg.reshape(-1), L_rpca[:,0]), ssim_rpca, t_rpca])
CUR_vals   = np.array([snr_db(bg.reshape(-1), L_cur[:,0]),  ssim_cur,  t_cur])
IRCUR_vals = np.array([snr_db(bg.reshape(-1), L_ircur[:,0]), ssim_ircur, t_ircur])


data = [RPCA_vals, CUR_vals, IRCUR_vals]
names = ["RPCA", "CUR", "IRCUR"]
colors = ["#1f77b4", "#2ca02c", "#d62728"]

angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False).tolist()
angles += angles[:1]  # close loop

plt.figure(figsize=(8,8))
for i, vals in enumerate(data):
    vals = vals.tolist()
    vals += vals[:1]
    plt.polar(angles, vals, marker='o', label=names[i], linewidth=2)

plt.xticks(angles[:-1], labels)
plt.title("Method Comparison (Radar Chart)", fontsize=16)
plt.legend(loc='upper right')
plt.show()

"""**6. TENSOR EXPERIMENTS**"""

X = build_tensor(bg, frames=10)

# Tucker
t1=time.time()
T_tucker = tucker_reconstruct(X)
t_tucker = time.time()-t1

# CP
t1=time.time()
T_cp = cp_reconstruct(X, rank=5)
t_cp = time.time()-t1

# RTCUR
t1=time.time()
T_rtcur, _ = rtcur_reconstruct(X, (10,10,3))
t_rtcur = time.time()-t1

print("Tucker SNR:", snr_db(X[:,:,0], T_tucker[:,:,0]))
print("CP SNR:", snr_db(X[:,:,0], T_cp[:,:,0]))
print("RTCUR SNR:", snr_db(X[:,:,0], T_rtcur[:,:,0]))

"""Tensor Method Comparison Bar Plot"""

methods = ["Tucker", "CP", "RTCUR"]
snr_vals = [
    snr_db(X[:,:,0], T_tucker[:,:,0]),
    snr_db(X[:,:,0], T_cp[:,:,0]),
    snr_db(X[:,:,0], T_rtcur[:,:,0])
]

plt.figure(figsize=(8,5))
plt.bar(methods, snr_vals, color=["#4C72B0", "#55A868", "#C44E52"])
plt.title("Tensor Methods SNR Comparison", fontsize=16)
plt.ylabel("SNR (dB)")
plt.grid(axis='y', alpha=0.4)
plt.show()

"""Tensor Reconstruction Comparison"""

plt.figure(figsize=(14,6))

plt.subplot(1,4,1)
plt.imshow(X[:,:,0], cmap='gray')
plt.title("Original Frame")
plt.axis('off')

plt.subplot(1,4,2)
plt.imshow(T_tucker[:,:,0], cmap='gray')
plt.title("Tucker Recon")
plt.axis('off')

plt.subplot(1,4,3)
plt.imshow(T_cp[:,:,0], cmap='gray')
plt.title("CP Recon")
plt.axis('off')

plt.subplot(1,4,4)
plt.imshow(T_rtcur[:,:,0], cmap='gray')
plt.title("RTCUR Recon")
plt.axis('off')

plt.suptitle("Tensor Method Reconstruction Comparison", fontsize=18, weight='bold')
plt.tight_layout()
plt.show()

"""Tensor Reconstruction Error Heatmaps"""

plt.figure(figsize=(14,6))

# Errors
err_tucker = np.abs(X[:,:,0] - T_tucker[:,:,0])
err_cp     = np.abs(X[:,:,0] - T_cp[:,:,0])
err_rtcur  = np.abs(X[:,:,0] - T_rtcur[:,:,0])

plt.subplot(1,3,1)
plt.imshow(err_tucker, cmap='inferno')
plt.title("Tucker Error Heatmap")
plt.colorbar(); plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(err_cp, cmap='inferno')
plt.title("CP Error Heatmap")
plt.colorbar(); plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(err_rtcur, cmap='inferno')
plt.title("RTCUR Error Heatmap")
plt.colorbar(); plt.axis('off')

plt.suptitle("Tensor Reconstruction Error Maps", fontsize=18, weight='bold')
plt.tight_layout()
plt.show()

"""Tensor Radar Chart"""

labels = np.array(["SNR", "Runtime"])
T_vals = np.array([
    [snr_db(X[:,:,0], T_tucker[:,:,0]), t_tucker],
    [snr_db(X[:,:,0], T_cp[:,:,0]),     t_cp],
    [snr_db(X[:,:,0], T_rtcur[:,:,0]),  t_rtcur]
])

names = ["Tucker", "CP", "RTCUR"]
angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False).tolist()
angles += angles[:1]

plt.figure(figsize=(8,8))
for i, vals in enumerate(T_vals):
    vals = vals.tolist()
    vals += vals[:1]
    plt.polar(angles, vals, marker="o", label=names[i], linewidth=2)

plt.xticks(angles[:-1], labels)
plt.title("Tensor Method Comparison (Radar Chart)", fontsize=16)
plt.legend(loc="upper right")
plt.show()

"""**7. VIDEO EXPERIMENT**"""

def extract_video_frames(path, scale=0.25):
    cap = cv2.VideoCapture(path)
    frames = []
    while True:
        ret, f = cap.read()
        if not ret:
            break
        g = cv2.cvtColor(f, cv2.COLOR_BGR2GRAY)
        g = cv2.resize(g, None, fx=scale, fy=scale)
        frames.append(g)
    cap.release()
    return frames

video = extract_video_frames("/content/sample.mp4")

video = video[:20]
H, W = video[0].shape

D = np.column_stack([f.reshape(-1) for f in video])

print("\nRunning Matrix RPCA...")
L_rpca, S_rpca = rpca(D)

print("Running Matrix CUR...")
L_cur = cur_decomposition(D, k=10)
S_cur = D - L_cur

print("Running Matrix IRCUR...")
L_ircur, S_ircur = ircur(D, r=10)

print("\nRunning Tensor Tucker...")
X_video = np.stack(video, axis=2)
T_tucker_video = tucker_reconstruct(X_video, ranks=(H//4, W//4, 5))

print("Running Tensor CP...")
T_cp_video = cp_reconstruct(X_video, rank=5)

print("Running Tensor RTCUR...")
T_rtcur_video, _ = rtcur_reconstruct(X_video, ranks=(H//4, W//4, 5))

plt.figure(figsize=(16,12))

images = [
    ("Original Frame",       video[0]),

    # Matrix methods
    ("RPCA Background",      L_rpca[:,0].reshape(H,W)),
    ("RPCA Foreground",      S_rpca[:,0].reshape(H,W)),

    ("CUR Background",       L_cur[:,0].reshape(H,W)),
    ("CUR Foreground",       S_cur[:,0].reshape(H,W)),

    ("IRCUR Background",     L_ircur[:,0].reshape(H,W)),
    ("IRCUR Foreground",     S_ircur[:,0].reshape(H,W)),

    # Tensor methods
    ("Tucker Background",    T_tucker_video[:,:,0]),
    ("Tucker Foreground",    X_video[:,:,0] - T_tucker_video[:,:,0]),

    ("CP Background",        T_cp_video[:,:,0]),
    ("CP Foreground",        X_video[:,:,0] - T_cp_video[:,:,0]),

    ("RTCUR Background",     T_rtcur_video[:,:,0]),
    ("RTCUR Foreground",     X_video[:,:,0] - T_rtcur_video[:,:,0]),
]

for i, (title, img) in enumerate(images):
    plt.subplot(5,3,i+1)
    plt.imshow(img, cmap='gray')
    plt.title(title, fontsize=10)
    plt.axis('off')

plt.suptitle("Matrix + Tensor Based Video Background Separation", fontsize=18, weight='bold')
plt.tight_layout()
plt.show()